### ISSUE TITLE
how can we use partitioning field option the way we use in API or bq CLI..

### ISSUE THREAD

**Issue by hidarapaneni** [miraisolutions/spark-bigquery#8]
how can we use partitioning field option the way we use in API or bq CLI..

syntax in bq cli - --time_partitioning_field

Thanks for the Lib. its so good and helpful. biggest problem is with lib dependency issues

**Comment by tfindlay-au** [comment]
I dont believe partitioning was supported with this version of the Google Bigquery API.
With the pull request you should be able to use table decorators.

As for specifying partition fields, it doesn't appear to be supported in this library, but could be added, it looks like you would need to work it into `client/package.scala` and do something like:
```
      val tableDefinition = StandardTableDefinition.newBuilder()
        .setType(TableDefinition.Type.TABLE)
        .setSchema(schema)
        .setTimePartitioning(columnName)
        .build()
```
Good luck!

**Comment by hidarapaneni** [comment]
Thx for responding , I did not see urs earlier some how it was not notified. I tried to do that but its not letting me to add field(setField). i could able to set time partitioning  to Day and expiration time but not field or requirepartition filter. It's not giving me those options. I even upgraded lib verion to latest, still not able to.

**Comment by hidarapaneni** [comment]
I got that working in load config instead of create table.. as my use case is more of parquet and while loading it does create table. Also supports schema evolution with allow scheme updates.
